// Queen Browser — AmmoOS field profile (auto-generated; not Firefox)
user_pref("general.useragent.override", "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) QueenBrowser/2026 AmmoOS/1.0 Gecko/20100101 QueenFieldEngine/128.0");
user_pref("general.useragent.vendor", "AmmoOS Field");
user_pref("general.useragent.vendorSub", "Queen Browser");
user_pref("general.useragent.product", "QueenBrowser");
user_pref("general.useragent.productSub", "2026");
user_pref("general.useragent.locale", "en-US");
user_pref("browser.startup.homepage", "http://127.0.0.1:9477/field");
user_pref("browser.startup.page", 1);
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.aboutwelcome.enabled", false);
user_pref("browser.aboutConfig.showWarning", false);
user_pref("browser.rights.3.shown", true);
user_pref("browser.rights.override.uri", "");
user_pref("identity.fxaccount.enabled", false);
user_pref("identity.fxaccounts.enabled", false);
user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.unified", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("app.update.enabled", false);
user_pref("app.update.auto", false);
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.showSponsored", false);
user_pref("browser.newtabpage.activity-stream.discoverystream.enabled", false);
user_pref("browser.tabs.firefox-view", false);
user_pref("extensions.pocket.enabled", false);
user_pref("browser.pocket.enabled", false);
user_pref("browser.search.defaultenginename", "DuckDuckGo");
user_pref("browser.urlbar.placeholderName", "Queen Browser");
user_pref("browser.fullscreen.autohide", true);
user_pref("full-screen-api.ignore-widgets", true);
user_pref("browser.tabs.inTitlebar", 0);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("browser.tabs.unloadOnLowMemory", true);
user_pref("dom.ipc.processCount", 8);
user_pref("gfx.webrender.all", true);
