[sdl]
fullscreen=false
output=surface
autolock=false

[cpu]
core=auto
cputype=auto
cycles=max

[render]
aspect=false
scaler=normal2x

[autoexec]
@echo off
mount c /bench/c
c:
echo RTX-DOS BENCH START
dir >nul
dir >nul
dir >nul
echo RTX-DOS BENCH END
exit